---
site_name: Ansible Compat Library
site_url: https://ansible.readthedocs.io/projects/compat/
repo_url: https://github.com/ansible/ansible-compat
edit_uri: blob/main/docs/
copyright: Copyright © 2023 Red Hat, Inc.
docs_dir: docs
# strict: true
watch:
  - mkdocs.yml
  - src
  - docs

theme:
  name: ansible
  features:
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - toc.integrate
nav:
  - examples: index.md
  - api: api.md
plugins:
  - autorefs
  - search
  - material/tags
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            # heading_level: 2
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes

            show_submodules: no
            docstring_section_style: list
            members_order: alphabetical
            show_category_heading: no
            # cannot merge init into class due to parse error...
            # merge_init_into_class: yes
            # separate_signature: yes
            show_root_heading: yes
            show_signature_annotations: yes
            separate_signature: yes
            # show_bases: false
    # options:
    #   show_root_heading: true
    #   docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 2
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: ""
